### PR TITLE
from __future__ import print_function for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
https://docs.python.org/3/whatsnew/3.0.html#print-is-a-function

### CODE REVIEW

**Comment by skywind3000** [comment]
多谢，这个 PR你大概测试过吧？

**Comment by cclauss** [comment]
This repo does not have any tests but I ran the code of this PR thru [flake8](http://flake8.readthedocs.io) --select=E901,E999,F821,F822,F823 to ensure there are no Syntax Errors.

**Comment by skywind3000** [comment]
多谢

**Comment by skywind3000** [comment]
不好意思，我刚才 merge 了，但是发现和 python2.5不兼容，我路由器上只能跑 python2.5，所以我回滚了。

**Pull request merged**
